# This is a basic workflow to help you get started with Actions

name: Clean workflow

# Controls when the action will run. 
on:
 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_one:
    name: Clean
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: terpconnect.umd.edu
          username: rlagos
          password: Pleasework123@
          port: 22
          script: |
             unalias rm
             rm -rf ronlagss.github.io
